name: Manual-Push-to-EC2

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to EC2 on manual push
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout the files
        uses: actions/checkout@v3

      - name: Deploy to AWS EC2
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}
